tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "autojump"
brew "cask"
brew "cmake"
brew "docker"
brew "docker-compose"
brew "fzf"
brew "git"
brew "jq"
brew "macvim"
brew "mas"
brew "mono"
brew "node@10"
brew "the_silver_searcher"
brew "tree"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
cask "alfred"
cask "boostnote"
cask "brave-browser"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "keybase"
cask "logitech-gaming-software"
cask "postman"
cask "scroll-reverser"
cask "slack"
cask "tableplus"
cask "unity"
cask "unity-hub"
cask "visual-studio-code"
cask "zoomus"
cask "caskroom/fonts/font-fira-code"
mas "BetterSnapTool", id: 417375580
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
