tap "adoptopenjdk/openjdk"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "pivotal/tap"
tap "somdoron/formulae"
brew "autojump"
brew "awscli"
brew "grpc"
brew "bear"
brew "gnutls"
brew "emacs"
brew "cask"
brew "ccls"
brew "circleci"
brew "cmake"
brew "docker"
brew "docker-compose"
brew "fzf"
brew "git"
brew "gradle"
brew "htop"
brew "jq"
brew "ruby"
brew "macvim"
brew "mas"
brew "maven"
brew "neovim"
brew "nvm"
brew "python@3.8"
brew "ripgrep"
brew "sbt"
brew "the_silver_searcher"
brew "tree"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "pivotal/tap/springboot"
brew "somdoron/formulae/spacebar"
cask "adoptopenjdk8"
cask "alfred"
cask "amazon-music"
cask "brave-browser"
cask "discord"
cask "docker"
cask "dotnet-sdk"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "keybase"
cask "logitech-gaming-software"
cask "logitech-unifying"
cask "postman"
cask "scroll-reverser"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "zoomus"
mas "Be Focused", id: 973134470
mas "BetterSnapTool", id: 417375580
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
