export VOLTA_HOME="$HOME/.volta"

PATH="$PATH:$HOME/bin"
PATH="$PATH:/usr/local/bin"
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.cargo/bin"
export path

export EDITOR="$(which nvim)"
export LANG="en_US.UTF-8"
export BAT_THEME="TwoDark"

export FZF_BASE="$(which fzf)"
export FZF_DEFAULT_COMMAND="rg --files"
export FZF_DEFAULT_OPTS="-m --height 50% --border"
export FZF_CTRL_T_COMMAND="rg --files --follow --hidden --glob=\!.git"

source ~/.dotfiles/zsh_config/machine_specific.sh
