# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"
ZSH_CUSTOM=~/.oh-my-zsh/custom

plugins=(
  autojump
  brew
  fast-syntax-highlighting
  fzf
  fzf-tab
  git
  npm
  nvm
  ripgrep
  tmux
  yarn
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
# fi

# source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

function _clear () {
  zle && { zle send-break; zle -R }
}

function _re-source () {
  printf "reloading..."
  source ~/.zshrc
  source ~/.zshenv
  printf "done\n"
  _clear
}
zle -N _re-source

function _kill-port () {
  process_id="$(lsof -P -i TCP -s TCP:LISTEN | fzf -m | awk '{print $2}')"
  if [[ -n $process_id ]]
  then
    eval "kill -9 $process_id"
    echo "killed pid:$process_id"
  else
    echo "no pid selected"
  fi
  _clear
}
zle -N _kill-port

# User configuration
unsetopt share_history

bindkey '^ ' autosuggest-accept
bindkey '^h' backward-char
bindkey '^l' forward-char
bindkey '^b' backward-word
bindkey '^w' forward-word
bindkey '^e' _re-source
bindkey '^ko' _kill-port

bindkey -s '^l' 'cd ~/workspace/octanner/$(ls ~/workspace/octanner | fzf)^M'
bindkey -s '^g' '$(git branch | fzf)^M'
bindkey -s '^o' 'nvim^M'

# alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Helpers/jsc'

# autoload -Uz compinit; compinit
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
