# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

plugins=(
  fast-syntax-highlighting
  fzf
  fzf-tab
  git
  tmux
  zsh-autosuggestions
  spaceship-vi-mode
)

source $ZSH/oh-my-zsh.sh

# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
# fi

# source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

function _clear () {
  zle && { zle send-break; zle -R }
}

function _re-source () {
  printf "reloading...\n"
  exec zsh
}
zle -N _re-source

function _kill-port () {
  process_id="$(lsof -P -i TCP -s TCP:LISTEN | fzf -m | awk '{print $2}')"
  if [[ -n $process_id ]]
  then
    eval "kill -9 $process_id"
    echo "killed pid:$process_id"
  else
    echo "no pid selected"
  fi
  _clear
}
zle -N _kill-port

function _kitty-opener () {
  kitty-opener
}
zle -N _kitty-opener

# User configuration
unsetopt share_history

# vi mode
bindkey -v
spaceship add --before char vi_mode
eval spaceship_vi_mode_enable

bindkey '^h' backward-char
bindkey '^l' forward-char
bindkey '^b' backward-word
bindkey '^w' forward-word
bindkey -M viins '^ ' autosuggest-accept
bindkey -M viins '^ko' _kill-port
bindkey -M vicmd '_' vi-beginning-of-line 
bindkey -M vicmd 'g_' vi-end-of-line 
bindkey -M viins '^kp' _kitty-opener

bindkey -s '^g' '$(git branch | fzf)^M'
bindkey -s '^o' 'nvim^M'

alias tf=terraform
alias pn=pnpm
alias lg=lazygit
alias e="$EDITOR"
# alias e='NVIM_APPNAME=lvim nvim'
alias cat="bat"
alias re=_re-source

# alias jsc='/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Helpers/jsc'

# add JAVA_HOME dynamically to path
. ~/.asdf/plugins/java/set-java-home.zsh

# autoload -Uz compinit; compinit
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(~/.local/bin/mise activate zsh)"
