# TODO handle linux and macos
set -x PATH "$PATH:$HOME/bin"
set -x PATH "$PATH:/usr/local/bin"
set -x PATH "$PATH:/usr/local/share/dotnet"
set -x PATH "$PATH:$HOME/.dotnet/tools"
set -x PATH "$PATH:$HOME/bin/jdk/Contents/Home/bin"
set -x PATH "$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
set -x PATH "$PATH:$HOME/.cargo/bin"
set -x PATH "$PATH:/usr/local/opt/make/libexec/gnubin"
set -x PATH "$PATH:/usr/local/opt/openssl@1.1/bin"
set -x PATH "$PATH:/usr/local/lib/nodejs/node-v16.13.1-linux-x64/bin"
set -x PATH "$PATH:$HOME/dotnet"

set -x DOTNET_ROOT "$HOME/dotnet"
set -x LANG "en_US.UTF-8"
set -x LC_CTYPE "en_US.UTF-8"
set -x LC_ALL "en_US.UTF-8"
set -x ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR "/usr/local/share/zsh-syntax-highlighting/highlighters"
set -x ASPNETCORE_ENVIRONMENT "Development"
set -x ASPNETCORE_HTTPS_PORT "5001"
set -x JAVA_HOME "/usr/bin"
set -x MONO_GAC_PREFIX "/usr/local"
set -x BAT_THEME "TwoDark"

set -x FZF_BASE "/usr/local/bin/fzf"
set -x FZF_DEFAULT_COMMAND "rg --files"
set -x FZF_DEFAULT_OPTS "-m --height 50% --border"
set -x FZF_CTRL_T_COMMAND "rg --files --follow --hidden --glob=\!.git"
